export const MOTIVATION_QUOTES = [
  // 🌅 Early Achievement
  { quote: "You didn’t wait for the perfect moment — you made one.", author: "Momentum" },
  { quote: "Progress is louder than excuses.", author: "Discipline" },
  { quote: "You just took the step 99% of people only plan to.", author: "Action" },
  { quote: "This tiny win echoes into every tomorrow.", author: "Consistency" },
  { quote: "You didn’t need motivation — you chose purpose.", author: "Focus" },

  // ⚙️ Discipline & Flow
  { quote: "Each tick of the clock just recorded your discipline.", author: "Time" },
  { quote: "You’re not chasing motivation — you’re building systems.", author: "Process" },
  { quote: "This is how success feels: quiet, persistent, and real.", author: "Growth" },
  { quote: "Every completed task reprogrammed your brain for greatness.", author: "Neuroscience" },
  { quote: "Your future self just whispered — 'thank you.'", author: "The Future You" },

  // 🔥 Dopamine & Wins
  { quote: "That feeling? It’s dopamine meeting destiny.", author: "Focus" },
  { quote: "Your brain is literally celebrating progress right now.", author: "Biology" },
  { quote: "One task done — one more version of you unlocked.", author: "Evolution" },
  { quote: "You are training your neurons to believe in you.", author: "Neural Rewire" },
  { quote: "Tiny victories. Massive rewiring.", author: "Discipline" },

  // 💪 Consistency Builds Strength
  { quote: "Consistency is your superpower — and you just used it.", author: "Habit" },
  { quote: "Brick by brick, you’re building unshakeable discipline.", author: "Grit" },
  { quote: "The fire inside you doesn’t fade — it compounds.", author: "Persistence" },
  { quote: "Every time you finish a task, you prove your potential was real.", author: "Reality" },
  { quote: "No applause needed. Progress noticed.", author: "Calm Achievement" },

  // 🌠 Momentum Moments
  { quote: "Momentum loves you now — don’t slow down.", author: "Flow" },
  { quote: "Discipline started the engine. Dopamine just pressed turbo.", author: "Performance" },
  { quote: "This isn’t luck — it’s calibration.", author: "Mindset" },
  { quote: "You’ve crossed another invisible line few ever do.", author: "Elite Zone" },
  { quote: "Your habits are silently compounding behind the scenes.", author: "The Algorithm" },

  // 🧠 Mental Fortitude
  { quote: "Your resistance broke. Progress slipped through.", author: "Willpower" },
  { quote: "The hardest part is always the start. You already passed it.", author: "Momentum" },
  { quote: "Your focus cut through noise like a laser.", author: "Concentration" },
  { quote: "Every finished task is proof: your word means something.", author: "Integrity" },
  { quote: "You’ve rewritten a line of your identity code.", author: "Neural Rewrite" },

  // 🧩 Self-Reflection
  { quote: "You are no longer trying — you’re becoming.", author: "Identity" },
  { quote: "This moment will echo as proof you didn’t give up.", author: "Legacy" },
  { quote: "Old you would’ve delayed this. New you just did it.", author: "Transformation" },
  { quote: "You didn’t wait for motivation — you created meaning.", author: "Purpose" },
  { quote: "Discipline is doing it when it doesn’t excite you. You just did.", author: "Truth" },

  // 🌈 Reward State
  { quote: "You’ve earned that deep breath — that’s victory oxygen.", author: "Reward" },
  { quote: "Rest feels different when you’ve earned it.", author: "Balance" },
  { quote: "Even silence sounds proud when you finish strong.", author: "Peace" },
  { quote: "This satisfaction is the ROI of consistency.", author: "Effort" },
  { quote: "Your brain just gave you a dopamine medal.", author: "Neuro Reward" },

  // 🚀 Big-Picture Reinforcement
  { quote: "Each win is a seed. Each seed becomes momentum.", author: "Cycle" },
  { quote: "The gap between goals and reality is consistency — and you’re closing it.", author: "Bridge" },
  { quote: "You are no longer hoping for change — you’re causing it.", author: "Impact" },
  { quote: "The version of you you wanted to become — is becoming you.", author: "Self-Actualization" },
  { quote: "Discipline is a lifestyle now, not a choice.", author: "Elevation" },

  // 🏆 High-Streak Motivation
  { quote: "This streak isn’t luck — it’s self-respect on repeat.", author: "Streaks" },
  { quote: "You’ve turned consistency into character.", author: "Identity" },
  { quote: "The streak doesn’t own you — you own the streak.", author: "Ownership" },
  { quote: "This day adds weight to your legacy.", author: "Reputation" },
  { quote: "You’re walking proof that momentum is a real muscle.", author: "Experience" },

  // ⚡ Energy / Flow Zone
  { quote: "This is flow — your brain on fire with progress.", author: "Neurochemistry" },
  { quote: "You just hit the state most chase for decades.", author: "Clarity" },
  { quote: "Your focus expanded time itself.", author: "Presence" },
  { quote: "You’ve entered the rare air of consistency.", author: "Altitude" },
  { quote: "The universe quietly shifted — you chose action.", author: "Energy" },

  // 🧬 Mind Growth
  { quote: "Your neurons just celebrated a new connection.", author: "Learning" },
  { quote: "You didn’t finish a task — you evolved a little.", author: "Mind" },
  { quote: "You’re no longer waiting to become — you are.", author: "Awakening" },
  { quote: "This win reshaped your brain’s belief loop.", author: "Neuroplasticity" },
  { quote: "You taught your subconscious who’s in charge.", author: "Command" },

  // 💥 Power Surge
  { quote: "That click wasn’t small — it was electric.", author: "Current" },
  { quote: "You don’t chase motivation anymore. You *are* motivation.", author: "Identity" },
  { quote: "Every tick completed adds a spark to your empire.", author: "Creator" },
  { quote: "Your effort is louder than your doubt.", author: "Courage" },
  { quote: "You didn’t find power — you built it.", author: "Will" },

  // 🌙 End of Day Reflection
  { quote: "The sun set on a day you conquered.", author: "Night" },
  { quote: "You’ll sleep well — discipline brings peace.", author: "Gratitude" },
  { quote: "You met your goals. That’s how peace feels.", author: "Serenity" },
  { quote: "You did what you said you would. That’s integrity defined.", author: "Virtue" },
  { quote: "You’re closing the day with momentum — not regret.", author: "Stillness" },

  // ✨ Future-Focused
  { quote: "Tomorrow just got easier — because you showed up today.", author: "Continuum" },
  { quote: "Momentum will remember you tomorrow.", author: "Memory" },
  { quote: "You just made future-you’s life easier.", author: "Gratitude" },
  { quote: "Every finished task is a message to your future: ‘We’re winning.’", author: "Trajectory" },
  { quote: "Discipline today, dominance tomorrow.", author: "Progression" },

  // 🔮 Bonus Deep Lines
  { quote: "The grind is sacred because it shapes you in silence.", author: "Philosophy" },
  { quote: "You’ve become the person your excuses fear.", author: "Power" },
  { quote: "Every task you complete teaches you control.", author: "Mastery" },
  { quote: "You didn’t find motivation — you found meaning.", author: "Clarity" },
  { quote: "This moment is proof: your potential was real all along.", author: "Proof" },
  
  // --- 420 NEW QUOTES START HERE ---

  // 🛡️ Overcoming Resistance
  { quote: "Procrastination whispered. You shouted back 'no'.", author: "Willpower" },
  { quote: "You just stared down resistance and made it blink first.", author: "Grit" },
  { quote: "That friction you felt? It just made you stronger.", author: "Growth" },
  { quote: "You just proved your discipline is stronger than your doubt.", author: "Conviction" },
  { quote: "The path of least resistance is boring. You chose the path of growth.", author: "Choice" },
  { quote: "You just did the hard thing. That's the only thing that matters.", author: "Action" },
  { quote: "Doubt is a dragon. You just pulled its teeth.", author: "Courage" },
  { quote: "You didn't feel like it. You did it anyway. That's power.", author: "Discipline" },
  { quote: "Resistance is just a sign you're moving in the right direction.", author: "The Compass" },
  { quote: "You just broke through the wall of 'later'.", author: "Now" },
  { quote: "The voice that said 'stop' just got weaker.", author: "Command" },
  { quote: "You just did what 99% of people delay.", author: "The 1%" },
  { quote: "That's one more rep against the weight of procrastination.", author: "Strength" },
  { quote: "You just took energy from your excuses and gave it to your goals.", author: "Transmutation" },
  { quote: "The comfort zone just got smaller in your rear-view mirror.", author: "Expansion" },
  { quote: "You just chose the creator over the consumer.", author: "Identity" },
  { quote: "That 'ugh' feeling was just a tollbooth. You paid the toll.", author: "Progress" },
  { quote: "The path to easy is through hard. You're on the path.", author: "Truth" },
  { quote: "You just acted in spite of fear. That's bravery.", author: "Courage" },
  { quote: "Every time you beat resistance, you level up.", author: "Evolution" },

  // 🔁 The Habit Loop
  { quote: "Cue. Routine. Reward. You just completed the loop.", author: "The Habit Loop" },
  { quote: "Another repetition. Another neural pathway strengthened.", author: "Neuroplasticity" },
  { quote: "You're making consistency your new default setting.", author: "Automation" },
  { quote: "This is how you install a new belief system: one action at a time.", author: "Upgrade" },
  { quote: "Your habits are your armor. You just polished it.", author: "Defense" },
  { quote: "That wasn't one action. It was a vote for a new identity.", author: "Identity" },
  { quote: "The chain of habit is built link by link. You just added a link.", author: "Strength" },
  { quote: "You're no longer 'building' the habit. You *are* the habit.", author: "Embodiment" },
  { quote: "This is the sound of automaticity being born.", author: "System" },
  { quote: "You just made it easier to do this again tomorrow.", author: "Compounding" },
  { quote: "A new habit is a new future. You just took a step into it.", author: "Trajectory" },
  { quote: "You just fed the right wolf.", author: "The Parable" },
  { quote: "This is how you make your future self inevitable.", author: "Destiny" },
  { quote: "You're replacing old code with a better algorithm.", author: "The Programmer" },
  { quote: "This is no longer a 'should'. It's a 'must'.", author: "Conviction" },
  { quote: "The consistency code is compiling in your brain.", author: "Neuroscience" },
  { quote: "You just acted out your new identity.", author: "Proof" },
  { quote: "This repetition is carving a new groove in your mind.", author: "Habit" },
  { quote: "The best habits are formed in these quiet, unseen moments.", author: "Silence" },
  { quote: "You're not just doing. You're becoming.", author: "Transformation" },

  // 📈 The Compound Effect
  { quote: "This small effort just added 1% to your growth.", author: "Compounding" },
  { quote: "This won't just pay off today. It'll pay off a year from now.", author: "Interest" },
  { quote: "The seeds of today are the forest of tomorrow. You just planted one.", author: "Growth" },
  { quote: "You're building a tower. This was another essential brick.", author: "Architecture" },
  { quote: "This tiny action just sent a massive ripple forward in time.", author: "Momentum" },
  { quote: "Small hinges swing big doors. You just pushed a hinge.", author: "Leverage" },
  { quote: "This win isn't just +1. It's x1.01.", author: "Mathematics" },
  { quote: "Your future self is built on the choices of today. Good choice.", author: "The Future" },
  { quote: "This is the unsexy work that leads to spectacular results.", author: "Process" },
  { quote: "The avalanche of success starts with one small pebble. This was it.", author: "Cause & Effect" },
  { quote: "You're not just adding; you're multiplying.", author: "Compounding" },
  { quote: "This is a deposit in the bank of your future self.", author: "Investment" },
  { quote: "Greatness is just consistency, compounded.", author: "Truth" },
  { quote: "You can't see the full result yet, but the algorithm is working.", author: "The System" },
  { quote: "This is how you get exponentially better.", author: "Growth" },
  { quote: "This action just made every future action slightly easier.", author: "Physics" },
  { quote: "The 'overnight success' is built on 1,000 of these moments.", author: "Reality" },
  { quote: "You just invested in your 10-year-from-now self.", author: "Legacy" },
  { quote: "This is the daily dividend of discipline.", author: "Reward" },
  { quote: "The mountain is moved one stone at a time. You just moved a stone.", author: "Persistence" },

  // 🧘 Deep Work Achieved
  { quote: "You just silenced the chaos and entered the zone.", author: "Deep Work" },
  { quote: "That wasn't just work; that was flow.", author: "Flow State" },
  { quote: "Distraction knocked. You didn't answer.", author: "Focus" },
  { quote: "You just mined value from your own attention.", author: "Clarity" },
  { quote: "This is the superpower of the 21st century. You just used it.", author: "Focus" },
  { quote: "You just proved your mind is your own.", author: "Sovereignty" },
  { quote: "The noise faded. Your signal got stronger.", author: "Signal" },
  { quote: "You just spent time in the state of high performance.", author: "Elite Zone" },
  { quote: "This is how you produce world-class results.", author: "Mastery" },
  { quote: "You just traded cheap distraction for deep satisfaction.", author: "Upgrade" },
  { quote: "You just tapped into your brain's highest gear.", author: "Performance" },
  { quote: "Attention is your most valuable currency. You just invested it wisely.", author: "Wealth" },
  { quote: "You didn't just 'do' the task. You *were* the task.", author: "Presence" },
  { quote: "That was an hour of 'lion' focus, not 'sheep' grazing.", author: "Power" },
  { quote: "You just trained your brain to be a laser.", author: "Concentration" },
  { quote: "The world is full of noise. You just created a masterpiece of quiet.", author: "Calm" },
  { quote: "This is the feeling of being truly productive, not just 'busy'.", author: "Effectiveness" },
  { quote: "You just built a fortress of focus.", author: "Discipline" },
  { quote: "Every moment in flow rewires your brain for more flow.", author: "Cycle" },
  { quote: "The results of this one session will echo for days.", author: "Impact" },

  // 👤 Identity Forged
  { quote: "You just cast another vote for the person you are becoming.", author: "Identity" },
  { quote: "This is no longer an 'act'. This is who you are now.", author: "Becoming" },
  { quote: "You are the sum of your actions. You just got better.", author: "Truth" },
  { quote: "Your character is built in these small moments of integrity.", author: "Character" },
  { quote: "You just acted as the person you want to be.", author: "Proof" },
  { quote: "This is how you become your own hero.", author: "Self-Respect" },
  { quote: "You're not 'trying' to be disciplined. You *are* disciplined.", author: "Identity" },
  { quote: "The 'old you' is now history.", author: "Evolution" },
  { quote: "You just signed a new contract with yourself. In ink.", author: "Commitment" },
  { quote: "This action just confirmed your new identity.", author: "Alignment" },
  { quote: "You're no longer in rehearsal. This is the performance.", author: "Action" },
  { quote: "This is self-love in its most powerful form: action.", author: "Self-Love" },
  { quote: "You just showed up for yourself. That's the deepest trust.", author: "Integrity" },
  { quote: "The person who 'can't' just left the building.", author: "Power" },
  { quote: "You're literally inventing yourself with every choice.", author: "Creation" },
  { quote: "This is how you earn your own respect.", author: "Honor" },
  { quote: "You just closed the gap between who you are and who you want to be.", author: "Alignment" },
  { quote: "This is the uniform of your new self. You just put it on.", author: "Identity" },
  { quote: "You just behaved like the 2.0 version of you.", author: "Upgrade" },
  { quote: "This is how you build a reputation with yourself.", author: "Trust" },

  // 🎯 Purpose & Intention
  { quote: "You just aligned your action with your 'why'.", author: "Purpose" },
  { quote: "This wasn't just a task; it was a choice for your future.", author: "Intention" },
  { quote: "Meaning isn't found; it's forged. You just swung the hammer.", author: "Meaning" },
  { quote: "You're not just busy; you're effective. There's a difference.", author: "Clarity" },
  { quote: "This action was a 'yes' to your biggest goals.", author: "Alignment" },
  { quote: "You just moved your 'North Star' a little closer.", author: "Direction" },
  { quote: "This is what it feels like to live on purpose.", author: "Intention" },
  { quote: "You just prioritized your mission over your mood.", author: "Purpose" },
  { quote: "This wasn't an accident. This was a deliberate step.", author: "Choice" },
  { quote: "You're not just checking boxes; you're building a legacy.", author: "Legacy" },
  { quote: "This is the work that matters. You just did it.", author: "Meaning" },
  { quote: "You just spent your energy on something that counts.", author: "Focus" },
  { quote: "This action connects directly to your ultimate vision.", author: "The Map" },
  { quote: "You're not wandering. You're walking a path you chose.", author: "Purpose" },
  { quote: "This is the antidote to regret: purposeful action.", author: "Wisdom" },
  { quote: "You just made a decision. The universe is already responding.", author: "Energy" },
  { quote: "You're not just 'getting through the day'. You're *using* the day.", author: "Intention" },
  { quote: "This is how you honor your own potential.", author: "Respect" },
  { quote: "Every task done with purpose feels like a victory.", author: "Focus" },
  { quote: "You just proved your 'why' is strong enough.", author: "Purpose" },

  // ✨ The Dopamine Spark
  { quote: "Feel that? That's the reward system saying 'YES, do that again'.", author: "Dopamine" },
  { quote: "Your brain just registered a 'win'. It's already hungry for the next one.", author: "Neuro Reward" },
  { quote: "This is the feeling of progress. Get addicted to this, not distraction.", author: "Biology" },
  { quote: "You just manufactured your own motivation. No external source needed.", author: "Chemistry" },
  { quote: "That's the natural high of achievement. It's powerful.", author: "Reward" },
  { quote: "Your brain's 'reward' pathway just lit up.", author: "Neuroscience" },
  { quote: "This feeling is your brain's way of saying 'Keep going'.", author: "Signal" },
  { quote: "You're creating a positive feedback loop that builds on itself.", author: "Cycle" },
  { quote: "This is the internal 'good job' that matters most.", author: "Self-Approval" },
  { quote: "You just gave your brain a reason to trust you.", author: "Dopamine" },
  { quote: "This is the feeling that breaks bad habits and builds new ones.", author: "Neuroplasticity" },
  { quote: "That little spark? That's the engine of momentum firing up.", author: "Ignition" },
  { quote: "You just earned this hit of satisfaction. Enjoy it.", author: "Reward" },
  { quote: "This is the most powerful motivation on earth: the one you create yourself.", author: "Power" },
  { quote: "Your brain is learning that discipline = reward.", author: "Learning" },
  { quote: "That feeling of 'yes!' is the sound of progress.", author: "Satisfaction" },
  { quote: "You're tapping into your body's own reward system.", author: "Biology" },
  { quote: "This is the carrot. You're teaching your brain to chase it.", author: "Training" },
  { quote: "This is the clean energy of intrinsic motivation.", author: "Fuel" },
  { quote: "You've just been paid in dopamine. Spend it on the next task.", author: "Currency" },

  // 🏁 The Finish Line
  { quote: "Task complete. Loop closed. Mind clear.", author: "Completion" },
  { quote: "You didn't just start. You finished. That's rare.", author: "Integrity" },
  { quote: "The best feeling in the world: 'Done'.", author: "Satisfaction" },
  { quote: "Another item moves from 'To-Do' to 'Done'. The best migration.", author: "Progress" },
  { quote: "You just closed a mental 'tab'. Feel the clarity?", author: "Focus" },
  { quote: "This is the reward for pushing through the messy middle.", author: "Grit" },
  { quote: "You saw it through to the end. That's character.", author: "Completion" },
  { quote: "One less thing on your mind. One more thing in your 'win' column.", author: "Clarity" },
  { quote: "You just killed a source of low-level anxiety.", author: "Peace" },
  { quote: "The high of finishing is better than the comfort of starting.", author: "Truth" },
  { quote: "This is how you build trust with yourself: you finish.", author: "Reliability" },
  { quote: "A finished task is a unit of progress, locked in forever.", author: "Proof" },
  { quote: "You just created a small pocket of order in a chaotic world.", author: "Control" },
  { quote: "That's a wrap. Your brain can now move on, stronger.", author: "Release" },
  { quote: "The circle is now complete. Well done.", author: "Completion" },
  { quote: "Breathe. That's the smell of victory.", author: "Satisfaction" },
  { quote: "You just set a new 'personal best' for discipline.", author: "Performance" },
  { quote: "This is the moment of 'click'. The piece just fit.", author: "Clarity" },
  { quote: "You didn't leave it 'good enough'. You made it 'done'.", author: "Excellence" },
  { quote: "That's one more wave of momentum you can ride.", author: "Flow" },

  // 🏋️ Inner Strength
  { quote: "This is what self-trust feels like. You're building it.", author: "Confidence" },
  { quote: "You just built a new layer of resilience.", author: "Fortitude" },
  { quote: "Your willpower is a muscle. You just did a rep.", author: "Strength" },
  { quote: "You just chose the harder path, and it made you stronger.", author: "Growth" },
  { quote: "This is what it feels like to be antifragile. You're getting stronger from stress.", author: "Resilience" },
  { quote: "You just proved you can count on yourself.", author: "Reliability" },
  { quote: "The discomfort was temporary. The strength is permanent.", author: "Gain" },
  { quote: "You're forging a new spine of discipline.", author: "Strength" },
  { quote: "This is how you build an unbreakable mind.", author: "Fortitude" },
  { quote: "You just flexed your 'show up' muscle.", author: "Consistency" },
  { quote: "That was a test of character. You passed.", author: "Integrity" },
  { quote: "You're building the kind of strength that doesn't need to yell.", author: "Calm Power" },
  { quote: "This is the source of all external power: internal discipline.", author: "Truth" },
  { quote: "Your future self will thank you for this 'rep'.", author: "Strength" },
  { quote: "You just reinforced the belief that you *can* do hard things.", author: "Belief" },
  { quote: "This is how you become the person who doesn't quit.", author: "Grit" },
  { quote: "You just increased your capacity for difficulty.", author: "Growth" },
  { quote: "This is the feeling of self-mastery. It's earned.", author: "Control" },
  { quote: "You're not just strong. You're *getting stronger*.", author: "Momentum" },
  { quote: "This is the quiet power of simply doing the work.", author: "Discipline" },

  // 🏗️ Architecting Tomorrow
  { quote: "Future You is already benefiting from this moment's work.", author: "The Future" },
  { quote: "You just laid a foundation stone for your long-term goals.", author: "Legacy" },
  { quote: "This action sent a ripple into your future. A good one.", author: "Cause & Effect" },
  { quote: "You're not just dreaming of the future; you're actively building it.", author: "Architect" },
  { quote: "This is how you make your 5-year-plan a reality.", author: "Strategy" },
  { quote: "You just bought yourself time and peace for tomorrow.", author: "Investment" },
  { quote: "The 'you' of tomorrow is grateful for the 'you' of today.", author: "Gratitude" },
  { quote: "This isn't just one task done. It's a better future secured.", author: "Progress" },
  { quote: "You're crafting your future, not just accepting it.", author: "Creator" },
  { quote: "This is a letter of intent to your future self. And you just kept it.", author: "Commitment" },
  { quote: "The future is a house you build. This was a perfect brick.", author: "Architecture" },
  { quote: "You just made your 'ideal day' a little more real.", author: "Vision" },
  { quote: "This is how you stack the deck in your own favor.", author: "Strategy" },
  { quote: "You're not just passing time; you're investing it.", author: "Wisdom" },
  { quote: "The 'you' of next week is already looking back at this moment with pride.", author: "The Future" },
  { quote: "This is how you turn a vision into a reality.", author: "Execution" },
  { quote: "You're planting a tree you'll enjoy the shade of for years.", author: "Legacy" },
  { quote: "This action just unlocked a new possible future.", author: "Potential" },
  { quote: "The bridge to your future is built of these actions.", author: "The Bridge" },
  { quote: "You just made a down payment on your future success.", author: "Investment" },

  // 🌌 Abstract Wins
  { quote: "You just bent your personal reality a little.", author: "Mind" },
  { quote: "The algorithm of your life just received a positive new input.", author: "The System" },
  { quote: "You just fed the 'wolf' of discipline, and it grew stronger.", author: "Choice" },
  { quote: "This is the quiet sound of you evolving.", author: "Silence" },
  { quote: "You just wrote a new line of code for 'You 2.0'.", author: "Upgrade" },
  { quote: "The universe rewards action. You just sent a signal.", author: "Energy" },
  { quote: "You just harmonized your thoughts, feelings, and actions.", author: "Alignment" },
  { quote: "This is what it feels like to be the 'cause', not the 'effect'.", author: "Power" },
  { quote: "You just changed your own weather.", author: "Mind" },
  { quote: "The tectonic plates of your identity just shifted. For the better.", author: "Transformation" },
  { quote: "You just made a choice that resonates on a higher frequency.", author: "Energy" },
  { quote: "This is how you build a life, not just live one.", author: "Creator" },
  { quote: "You just cleared a little more fog from your mind.", author: "Clarity" },
  { quote: "This action just anchored your new reality.", author: "Physics" },
  { quote: "You just chose order over entropy.", author: "Choice" },
  { quote: "This is the feeling of your potential being actualized.", author:"Becoming" },
  { quote: "You just turned a thought into a thing. That's magic.", author: "Creation" },
  { quote: "The path just became clearer because you took a step.", author: "The Path" },
  { quote: "You just taught your subconscious that you are in charge.", author: "Command" },
  { quote: "This is the feeling of 'clicking' into place.", author: "Alignment" },

  // 💡 Clarity & Focus
  { quote: "Your mind is clear. Your purpose is set. This is power.", author: "Clarity" },
  { quote: "You just cut through the 'maybe' and 'should' and found the 'did'.", author: "Action" },
  { quote: "This is the peace that comes from knowing exactly what to do.", author: "Focus" },
  { quote: "You just prioritized. That's the highest form of thinking.", author: "Strategy" },
  { quote: "The fog of 'too much' just cleared. This is the one thing.", author: "Clarity" },
  { quote: "You just proved you know the difference between 'urgent' and 'important'.", author: "Wisdom" },
  { quote: "This is the feeling of a mind that is a tool, not a tyrant.", author: "Control" },
  { quote: "You just eliminated a distraction. You gained a unit of power.", author: "Focus" },
  { quote: "Clarity of action is a superpower. You just used it.", author: "Clarity" },
  { quote: "You just said 'no' to a dozen other things, to say 'yes' to this.", author: "Focus" },
  { quote: "This is the feeling of a clean, organized mind.", author: "Peace" },
  { quote: "You just replaced confusion with completion.", author: "Action" },
  { quote: "Your focus is a resource. You just spent it perfectly.", author: "Investment" },
  { quote: "This is the calm confidence of knowing your next step.", author: "Clarity" },
  { quote: "You just transformed a vague goal into a concrete action.", author: "Execution" },
  { quote: "This is how you get 'unstuck'. One clear action.", author: "Momentum" },
  { quote: "You just took a complex problem and solved the first piece.", author: "Progress" },
  { quote: "This is the sound of your priorities clicking into place.", author: "Alignment" },
  { quote: "You just sharpened the blade of your mind.", author: "Focus" },
  { quote: "This is the result of 'essentialism' in practice.", author: "Clarity" },

  // 🌿 Small, Steady Growth
  { quote: "You don't need a quantum leap. You just need this steady step.", author: "Consistency" },
  { quote: "This is the quiet, invisible work that builds empires.", author: "Process" },
  { quote: "A little bit, every day. You're doing it now.", author: "Growth" },
  { quote: "This isn't a sprint. It's a marathon. And you just ran this mile well.", author: "Patience" },
  { quote: "You're not trying to be perfect. You're just trying to be better.", author: "Progress" },
  { quote: "This is the 1% win that leads to 100% transformation.", author: "Compounding" },
  { quote: "The oak tree grows slowly. So does your strength.", author: "Nature" },
  { quote: "This is the steady drip of water that carves stone.", author: "Persistence" },
  { quote: "You're not forcing it. You're building it. Sustainably.", author: "Balance" },
  { quote: "This is the 'boring' work that guarantees success.", author: "Discipline" },
  { quote: "Don't discount the small win. It's the most important one.", author: "Growth" },
  { quote: "You just showed up. That's 80% of the battle.", author: "Presence" },
  { quote: "This is how you build a foundation that can't be shaken.", author: "Stability" },
  { quote: "You're just watering the plant. The growth will come.", author: "Patience" },
  { quote: "This is the steady heartbeat of progress.", author: "Rhythm" },
  { quote: "This is the opposite of a 'get rich quick' scheme. This is 'get strong for sure'.", author: "Reality" },
  { quote: "You just made a small, smart choice. It adds up.", author: "Wisdom" },
  { quote: "This is the 'daily practice'. It's more powerful than 'one-time inspiration'.", author: "Habit" },
  { quote: "You're just laying the next brick. Perfectly.", author: "Craft" },
  { quote: "This is the sustainable path to mastery.", author: "Process" },
  
  // 🚀 Taking the Leap
  { quote: "You just did the 'scary' thing. And you survived. You thrived.", author: "Courage" },
  { quote: "That was the jump. The net appeared.", author: "Trust" },
  { quote: "You just stepped out of the comfort zone and into the 'growth zone'.", author: "Expansion" },
  { quote: "Fear was there. You just acted anyway.", author: "Bravery" },
  { quote: "You just took the risk your future self was hoping you would.", author: "Action" },
  { quote: "This is how you build courage: by using it.", author: "Strength" },
  { quote: "You just proved your 'why' is bigger than your 'what if'.", author: "Purpose" },
  { quote: "That was a 'character point'. You just earned it.", author: "Growth" },
  { quote: "You just leaned into the resistance. That's where the magic is.", author: "Edge" },
  { quote: "You didn't wait for confidence. You built it with action.", author: "Proof" },
  { quote: "That uncertainty you felt? That was the feeling of growth.", author: "Discomfort" },
  { quote: "You just beta-tested a new, braver version of you.", author: "Upgrade" },
  { quote: "You just closed your eyes and trusted your preparation.", author: "Leap" },
  { quote: "This is how you expand your 'possible'.", author: "Potential" },
  { quote: "You just chose the arena over the sidelines.", author: "Action" },
  { quote: "This is the work that separates the dreamer from the doer.", author: "Execution" },
  { quote: "You just put your skin in the game.", author: "Commitment" },
  { quote: "That was the 'point of no return'. You just crossed it.", author: "Momentum" },
  { quote: "You just turned a 'what if' into a 'what is'.", author: "Creation" },
  { quote: "This is how you find out what you're made of.", author: "Grit" },

  // 💡 'Aha!' Moments
  { quote: "It just 'clicked'. That's the sound of a new neural pathway.", author: "Insight" },
  { quote: "The solution appeared. Because you were *doing*, not just thinking.", author: "Action" },
  { quote: "You just connected two dots no one else saw.", author: "Creativity" },
  { quote: "That's it. The 'key' just turned in the 'lock'.", author: "Clarity" },
  { quote: "This is the 'eureka' that only comes from deep work.", author: "Discovery" },
  { quote: "You just saw the pattern in the chaos.", author: "Wisdom" },
  { quote: "The answer was 'do the work'. You just found it.", author: "Truth" },
  { quote: "This is the clarity that follows commitment.", author: "Focus" },
  { quote: "You just unlocked a new perspective.", author: "Insight" },
  { quote: "This is the 'level up' moment. You just earned it.", author: "Evolution" },
  { quote: "You just saw the 'matrix' behind the problem.", author: "Clarity" },
  { quote: "This is the reward for staying with the problem.", author: "Persistence" },
  { quote: "You just found the elegant solution.", author: "Simplicity" },
  { quote: "The 'how' just revealed itself, because you mastered the 'now'.", author: "Presence" },
  { quote: "You just found the leverage point.", author: "Strategy" },
  { quote: "This is the 'Aha!' that your brain rewards you with.", author: "Dopamine" },
  { quote: "You just turned a stumbling block into a stepping stone.", author: "Perspective" },
  { quote: "This is the 'click' of true understanding.", author: "Learning" },
  { quote: "You just found the 'signal' in the 'noise'.", author: "Focus" },
  { quote: "The puzzle piece just fit. Satisfying, isn't it?", author: "Completion" },

  // 🏆 Celebrating the Win
  { quote: "Acknowledge this. This is a real, tangible win.", author: "Celebration" },
  { quote: "You just set a standard. Now, meet it again tomorrow.", author: "Excellence" },
  { quote: "This is a victory. Pause for one second and feel it.", author: "Reward" },
  { quote: "You just gave yourself a reason to be proud.", author: "Self-Respect" },
  { quote: "This is what 'winning the day' looks like.", author: "Victory" },
  { quote: "You just added another 'W' to the column.", author: "Scoreboard" },
  { quote: "This is the result. This is what the work was for.", author: "Proof" },
  { quote: "You just did what you set out to do. That's success.", author: "Integrity" },
  { quote: "This is a 'milestone', not just a 'task'.", author: "Progress" },
  { quote: "You just raised your average.", author: "Performance" },
  { quote: "This is a moment to save in your 'evidence' folder.", author: "Belief" },
  { quote: "You just earned this feeling of accomplishment.", author: "Reward" },
  { quote: "This is the 'trophy' for the invisible, internal battle you just won.", author: "Grit" },
  { quote: "You just hit 'save' on a better version of you.", author: "Upgrade" },
  { quote: "This is the 'payoff'. It's real.", author: "Satisfaction" },
  { quote: "You just moved the needle. Measurably.", author: "Impact" },
  { quote: "This is the taste of victory. Remember it.", author: "Memory" },
  { quote: "This is you, keeping your promises to you.", author: "Trust" },
  { quote: "You just hit your 'personal record' for this moment.", author: "Excellence" },
  { quote: "This is the win. Small, maybe. But real.", author: "Victory" },

  // 🧘 Presence & Mindfulness
  { quote: "You weren't in the past or future. You were *here*. And you won.", author: "Presence" },
  { quote: "This is the feeling of being 100% 'on'.", author: "Flow" },
  { quote: "You just did one thing, with your whole mind.", author: "Focus" },
  { quote: "This is the power of 'now'. You just wielded it.", author: "Presence" },
  { quote: "You just anchored your mind to the task. And it held.", author: "Control" },
  { quote: "This is the feeling of being 'all in' on a single moment.", author: "Commitment" },
  { quote: "You just proved that where your attention goes, your energy flows.", author: "Physics" },
  { quote: "This is the state of 'mindful action'.", author: "Awareness" },
  { quote: "You just did the task, without being 'lost' in the task.", author: "Clarity" },
  { quote: "This is the 'eye of the storm'. You just found it.", author: "Calm" },
  { quote: "You just gave this single moment the respect it deserved.", author: "Presence" },
  { quote: "This is the sound of your mind being fully engaged.", author: "Flow" },
  { quote: "You just turned 'doing' into 'being'.", author: "Mindfulness" },
  { quote: "This is the focus that makes time disappear.", author: "Deep Work" },
  { quote: "You just shut out the world and opened up your mind.", author: "Focus" },
  { quote: "This is the peace of single-tasking.", author: "Simplicity" },
  { quote: "You just merged with the action. No separation.", author: "Flow" },
  { quote: "This is the 'Zen' of productivity.", author: "Clarity" },
  { quote: "You just gave 100% of your attention. And it paid off.", author: "Reward" },
  { quote: "This is the feeling of being centered, even in motion.", author: "Balance" },

  // 🤝 Connection & Integrity
  { quote: "You just kept a promise to yourself. That's the root of all confidence.", author: "Integrity" },
  { quote: "This action was in perfect alignment with your values.", author: "Alignment" },
  { quote: "You just proved your word is your bond. Especially to yourself.", author: "Trust" },
  { quote: "This is what 'walking the talk' feels like.", author: "Integrity" },
  { quote: "You just honored your commitment. That's character.", author: "Honor" },
  { quote: "This is how you build unbreakable self-respect.", author: "Self-Respect" },
  { quote: "Your actions and your goals are now in sync.", author: "Harmony" },
  { quote: "You just chose the 'you' you want to be.", author: "Identity" },
  { quote: "This is the feeling of being 'whole'. No part of you was fighting this.", author: "Alignment" },
  { quote: "You just built a bridge of trust between you and you.", author: "Connection" },
  { quote: "This is the feeling of 'rightness'. Your actions match your beliefs.", author: "Integrity" },
  { quote: "You just did what you said you would do. That's the definition of power.", author: "Power" },
  { quote: "This is how you become a person you can rely on.", author: "Reliability" },
  { quote: "You just closed the 'integrity gap'.", author: "Truth" },
  { quote: "This is the peace that comes from being true to your word.", author: "Serenity" },
  { quote: "You just proved that your 'yes' means 'yes'.", author: "Commitment" },
  { quote: "This is the foundation of self-love: keeping your own promises.", author: "Self-Love" },
  { quote: "You just acted as a person of high character.", author: "Virtue" },
  { quote: "This is the 'click' of values and actions aligning.", author: "Alignment" },
  { quote: "You just made yourself proud. That's the only approval you need.", author: "Sovereignty" },

  // 🔋 Recharged & Ready
  { quote: "This task is done. You are now charged up for the next one.", author: "Energy" },
  { quote: "You just turned 'willpower' into 'momentum'.", author: "Physics" },
  { quote: "This win didn't drain you. It *fueled* you.", author: "Fuel" },
  { quote: "You just created a new 'energy packet' for your brain.", author: "Momentum" },
  { quote: "This is the 'second wind' that comes from a small win.", author: "Energy" },
  { quote: "You just filled your 'progress bar' a little more.", author: "Charge" },
  { quote: "This is the 'on' switch for your motivation.", author: "Ignition" },
  { quote: "You just 'primed' your brain for more success.", author: "Neuroscience" },
  { quote: "This is the positive, clean energy of accomplishment.", author: "Fuel" },
  { quote: "You're not 'done for the day'. You're 'warmed up'.", author: "Performance" },
  { quote: "This is the 'upward spiral'. You just kicked it off.", author: "Cycle" },
  { quote: "You just proved that action creates energy.", author: "Truth" },
  { quote: "This is the feeling of 'reloading' your focus.", author: "Charge" },
  { quote: "You just tapped into a new reserve of 'get it done'.", author: "Energy" },
  { quote: "This isn't the end. This is the starting gun for the *next* win.", author: "Momentum" },
  { quote: "You just opened the floodgates of productivity.", author: "Flow" },
  { quote: "This is the 'spark' that lights the bigger fire.", author: "Ignition" },
  { quote: "You're not running on 'empty'. You're running on 'done'.", author: "Fuel" },
  { quote: "This is the 'catalyst' for a productive streak.", author: "Chemistry" },
  { quote: "You just built energy, not just spent it.", author: "Creation" },

  // 🌟 Final Polish
  { quote: "This is how you turn 'good' into 'great'.", author: "Excellence" },
  { quote: "You just added the 1% that makes all the difference.", author: "Mastery" },
  { quote: "This is the 'signature' on your work. And it's a good one.", author: "Craft" },
  { quote: "You didn't just 'do' it. You 'completed' it. Well.", author: "Quality" },
  { quote: "This is the 'extra mile'. There's no traffic here.", author: "Excellence" },
  { quote: "You just showed pride in your work. And it shows.", author: "Craftsmanship" },
  { quote: "This is the 'finish' that separates the amateur from the pro.", author: "Professionalism" },
  { quote: "You just took the time to do it right.", author: "Quality" },
  { quote: "This is the mark of the true artisan.", author: "Craft" },
  { quote: "You just added the 'polish'. Now it shines.", author: "Excellence" },
];