export const QUOTES = [
  { quote: "The world doesn't care about your potential. Only your results.", author: "The Iron Mindset" },
  { quote: "Power isn't given, it's taken.", author: "Anonymous" },
  { quote: "Work until your bank account looks like a phone number.", author: "Anonymous" },
  { quote: "If you don't build your dream, someone else will hire you to build theirs.", author: "Tony Gaskins" },
  { quote: "Destroy yourself in your work... or life will destroy you for being average.", author: "The Iron Mindset" },
  { quote: "The only way to guarantee failure is to never try.", author: "Anonymous" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { quote: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { quote: "The price of discipline is always less than the pain of regret.", author: "Anonymous" },
  { quote: "You can't have a million-dollar dream with a minimum-wage work ethic.", author: "Anonymous" },
  { quote: "Obsessed is just a word the lazy use to describe the dedicated.", author: "Anonymous" },
  { quote: "If you get tired, learn to rest, not to quit.", author: "Banksy" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
  { quote: "You don't get what you wish for. You get what you work for.", author: "Anonymous" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
  { quote: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous" },
  { quote: "The harder you work, the luckier you get.", author: "Gary Player" },
  { quote: "Excuses are the nails used to build a house of failure.", author: "Don Wilder" },
  { quote: "Do what is hard and your life will be easy. Do what is easy and your life will be hard.", author: "Anonymous" },
  { quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Anonymous" },
  { quote: "A lion doesn't concern himself with the opinion of sheep.", author: "Anonymous" },
  { quote: "Suffer the pain of discipline or suffer the pain of regret.", author: "Anonymous" },
  { quote: "Your competition is waking up.", author: "Anonymous" },
  { quote: "Victory is reserved for those who are willing to pay its price.", author: "Sun Tzu" },
  { quote: "Stop doubting yourself. Work hard and make it happen.", author: "Anonymous" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
  { quote: "It's not about having time. It's about making time.", author: "Anonymous" },
  { quote: "Be so good they can't ignore you.", author: "Steve Martin" },
  { quote: "The wolf on the hill is not as hungry as the wolf climbing the hill.", author: "Arnold Schwarzenegger" },
  { quote: "Nobody cares about your excuses. Nobody pities you for procrastinating. Nobody is going to coddle you. It's your life. Take responsibility.", author: "Anonymous" },
  { quote: "If you're not willing to work for it, don't complain about not having it.", author: "Anonymous" },
  { quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { quote: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { quote: "It's going to be hard, but hard is not impossible.", author: "Anonymous" },
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { quote: "Average is for the weak.", author: "Anonymous" },
  { quote: "While you're busy making excuses, someone else is getting ahead.", author: "Anonymous" },
  { quote: "Don't be afraid of being a beginner. Everyone was once.", author: "Anonymous" },
  { quote: "The cost of ambition is early mornings, long nights, and weekends.", author: "Anonymous" },
  { quote: "Hustle beats talent when talent doesn't hustle.", author: "Ross Simmonds" },
  { quote: "Your comfort zone will kill you.", author: "Anonymous" },
  { quote: "The master has failed more times than the beginner has even tried.", author: "Stephen McCranie" },
  { quote: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { quote: "You are what you do, not what you say you'll do.", author: "C.G. Jung" },
  { quote: "Champions are made when no one is watching.", author: "Anonymous" },
  { quote: "Stop waiting for the 'right time'. Time isn't waiting for you.", author: "Anonymous" },
  { quote: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
  { quote: "You can't cheat the grind. It knows how much you've invested.", author: "Anonymous" },
  { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { quote: "Prove them wrong.", author: "Anonymous" },
  { quote: "The only person you should try to be better than is the person you were yesterday.", author: "Anonymous" },
  { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { quote: "Success is never owned; it is rented. And the rent is due every day.", author: "Rory Vaden" },
  { quote: "The sun is up, the clock is ticking, and your goals aren't going to achieve themselves.", author: "Anonymous" },
  { quote: "Don't talk, act. Don't say, show. Don't promise, prove.", author: "Anonymous" },
  { quote: "The work will not do itself.", author: "Anonymous" },
  { quote: "Discomfort is the currency of success.", author: "Anonymous" },
  { quote: "If you want to be a lion, you must train with lions.", author: "Anonymous" },
  { quote: "The average person quits. Be better than average.", author: "Anonymous" },
  { quote: "Amateurs wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King" },
  { quote: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Anonymous" },
  { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { quote: "Comfort is the enemy of progress.", author: "P.T. Barnum" },
  { quote: "Work in silence. Let success be your noise.", author: "Frank Ocean" },
  { quote: "You're not tired. You're uninspired.", author: "Anonymous" },
  { quote: "The only limit is the one you set yourself.", author: "Anonymous" },
  { quote: "Someone else is working harder than you right now.", author: "Anonymous" },
  { quote: "You will never always be motivated. You have to learn to be disciplined.", author: "Anonymous" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "Excuses don't get results.", author: "Anonymous" },
  { quote: "The question isn't 'Who is going to let me?' It's 'Who is going to stop me?'", author: "Ayn Rand" },
  { quote: "Sleep is for those who are broke.", author: "50 Cent" },
  { quote: "You have to be relentless.", author: "Anonymous" },
  { quote: "Greatness is not a single act, but a habit of discipline.", author: "Anonymous" },
  { quote: "If you want to live a life you've never lived, you have to do things you've never done.", author: "Anonymous" },
  { quote: "Stop being afraid of what could go wrong and start being excited about what could go right.", author: "Anonymous" },
  { quote: "If you're the smartest person in the room, you're in the wrong room.", author: "Anonymous" },
  { quote: "The grind includes Friday and Saturday.", author: "Anonymous" },
  { quote: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Your potential is irrelevant. Your execution is all that matters.", author: "Anonymous" },
  { quote: "Be addicted to the process of becoming better.", author: "Anonymous" },
  { quote: "Mediocrity is a disease. Discipline is the cure.", author: "Anonymous" },
  { quote: "No one ever got rich working 9 to 5.", author: "Anonymous" },
  { quote: "Your excuses are boring.", author: "Anonymous" },
  { quote: "Become a monster. A monster of discipline. A monster of work ethic.", author: "The Iron Mindset" },
  { quote: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { quote: "The difference between who you are and who you want to be is what you do.", author: "Anonymous" },
  { quote: "A dream doesn't become reality through magic; it takes sweat, determination, and hard work.", author: "Colin Powell" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { quote: "The world is a jungle. You either fight and dominate or hide and evaporate.", author: "Anonymous" },
  { quote: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { quote: "It's you vs. you. Make sure you win.", author: "Anonymous" },
  { quote: "Don't wish for it. Work for it.", author: "Anonymous" },
  { quote: "The moment you feel like quitting is the moment you need to keep pushing.", author: "Anonymous" },
  { quote: "Outwork everyone.", author: "Anonymous" },
  { quote: "You can't build an empire by working 8 hours a day.", author: "Anonymous" },
  { quote: "You are your only limit.", author: "Anonymous" },
  { quote: "The work you put in today will be the foundation for your tomorrow.", author: "Anonymous" },
  { quote: "Don't be upset by the results you didn't get with the work you didn't do.", author: "Anonymous" },
  { quote: "If you're not obsessed with your life, you're wasting it.", author: "Anonymous" },
  { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
  { quote: "Be stubborn about your goals and flexible about your methods.", author: "Anonymous" },
  { quote: "Do the work. Especially when you don't feel like it.", author: "Anonymous" },
];

export const DEFAULT_TASKS = [
  { id: "1", name: "DSA", duration: 2, priority: 1 },
  { id: "2", name: "System Design", duration: 0.5, priority: 2 },
  { id: "3", name: "Data Science", duration: 1, priority: 3 },
  { id: "4", name: "Agentic AI", duration: 1, priority: 4 },
];
